---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: myweb
  name: myweb
spec:
  replicas: 10
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - image: harbor.its.local/library/myweb:latest
        imagePullPolicy: Always
        name: myweb
---
kind: Service
apiVersion: v1
metadata:
  name:  myweb
spec:
  selector:
    app:  myweb
  type:  LoadBalancer
  ports:
  - name:  http
    port:  80
    targetPort:  80
